### ISSUE TITLE
Some general questions...

### ISSUE THREAD

**Issue by telkins** [bluematador/cloud-core#9]
In "Extrapolate costs from the last:", there are several values from which to choose: value, hour, day, week.

**What does "value" mean?**

**Also, how accurate is all this?**  I have an AWS-based app that I can hit with requests, then I generate a forecast.  If I wait a minute or two, the next forecast is noticeably different.  There's no other traffic other than the traffic I'm generating.

Finally...some services appear to be missing.  I'm using Elasticache and an RDS instance as well as a NAT gateway.  None of them appear to be listed among the services.  **Can you help me to understand why some services may be missing?**

I hope it's OK to pose questions here.  If not, please let me know. 🤓

**Comment by mbarlocker** [comment]
This is a fine place to ask.

"value", in context, refers to "extrapolating costs from the last value". As in, assume that the last value is the most accurate, and make predictions based on the last value. This is good if you just made a release, and don't have an hour of data yet. The alternative would be to take the data over the last hour, or the last day, or the last week. Value is just the most recent data point, and will be incredibly volatile as a result.

Accuracy is a mixed bag. The math is accurate, but its predictions of your traffic won't be 100%. The tool was made to give an accurate representation of your current costs. If your current costs change, due to seasonality of data, new users, or churn, then you'll have to bake that into your analysis by adjusting the aggregation and extrapolation functions. I will point out that, if you don't have any data, the cost of just using the tool will register as a much higher amount than you anticipate. Where normally it's a rounding error, it can be substantial if it's the only data being generated.

As for missing services, we hoped to add many services, but it just hasn't materialized due to other focuses. We're always open to a pull request. Anyone with programming experience should be able to detect the patterns and write a new service in a few hours.

**Comment by telkins** [comment]
@mbarlocker Thanks for your help.  Much appreciated.
